services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Порт, на котором будет доступно React приложение
    environment:
      - REACT_APP_API_URL=http://localhost:7123